-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

hl.config({
  general = { gaps_in = 5, gaps_out = 12, border_size = 1 },
  decoration = { shadow = { enabled = false } },
  input = { kb_layout = "de", kb_variant = "nodeadkeys", kb_options = "" },
  animations = { enabled = false },
})

do
  local ok, wc = pcall(dofile, os.getenv("HOME") .. "/.cache/ryoku/hypr-colors.lua")
  local function rgb(h, f) if type(h) ~= "string" then h = f end return "rgb(" .. h:gsub("#", "") .. ")" end
  hl.config({ general = { ["col.active_border"] = { colors = { rgb(ok and wc and wc.active, "#e0563b"), rgb(ok and wc and wc.inactive, "#313a4d") }, angle = 45 } } })
end
hl.animation({ leaf = "borderangle", enabled = true, speed = 80.0, bezier = "linear", style = "loop" })
