# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D0D1D2
background         #683521
cursor             #7D6853

active_tab_foreground     #683521
active_tab_background     #D0D1D2
inactive_tab_foreground   #D0D1D2
inactive_tab_background   #683521

active_border_color   #D0D1D2
inactive_border_color #683521
bell_border_color     #B58362

color0      #9C9D9F
color1		#B58362
color2		#708B72
color3		#8F5A44
color4		#8D563F
color5		#6A6150
color6		#734836
color7		#6D4F3B
color8		#A97A5B
color9		#F1AF83
color10		#95BA99
color11		#BF785A
color12		#BC7255
color13		#8D816B
color14		#996148
color15		#F0CEB8
