-- Generated by Ryoku Settings (Keybinds page); change it in the GUI, not here.
return {
	["SUPER + grave"] = "SUPER + SHIFT + grave",
	["SUPER + grave"] = "SUPER + SHIFT + grave",
	["SUPER + grave"] = "SUPER + SHIFT + grave",
	["SUPER + grave"] = "SUPER + SHIFT + grave",
	["SUPER + grave"] = "SUPER + SHIFT + grave",
	["SUPER + grave"] = "SUPER + SHIFT + grave",
	["SUPER + grave"] = "SUPER + SHIFT + grave",
	["SUPER + grave"] = "SUPER + SHIFT + grave",
	["SUPER + grave"] = "SUPER + SHIFT + grave",
	["SUPER + grave"] = "SUPER + SHIFT + grave",
}
