#!/usr/bin/env bash
# Shared by copy-from-system.sh and copy-to-system.sh: which files under
# ~/.config belong to Ryoku rather than to this repo.

# On a Ryoku system most of ~/.config is laid down by Ryoku itself: shipped
# defaults (mirrored in /usr/share/ryoku/config) that every update replaces,
# files its theme daemon and settings GUI render, and per-machine state. Only
# what the user owns belongs in this repo; exporting the rest fights Ryoku on
# restore and, fed to `ryoku import`, makes user-includes load themselves.
RYOKU_SHIPPED="/usr/share/ryoku/config"

# Shipped as a starting point but owned by the user from then on.
RYOKU_USER_OWNED=(
    "hypr/user.lua"
    "ryoku/user_edits/*"
)

# Per-machine or rendered state with no marker line to recognise it by.
RYOKU_STATE=(
    "fish/fish_variables"
    "kitty/current-theme.conf"
    "kitty/current-font.conf"
    "qt6ct/colors/ryoku.conf"
    "hypr/CHANGELOG.md"
    "ryoku/monitors-applied.json"
    "ryoku/output-profiles/*"
    "ryoku/import-backups/*"
)

# Shipped files people hand-edit, each with the user override Ryoku loads
# instead. Other shipped files differ because Ryoku rewrites them itself.
declare -A RYOKU_OVERRIDE_FOR=(
    ["fish/config.fish"]="fish/user.fish"
    ["kitty/kitty.conf"]="kitty/user.conf"
    ["hypr/hyprland.lua"]="hypr/user.lua"
)

RYOKU_WARNINGS=()

is_ryoku_system() {
    [[ -d "$RYOKU_SHIPPED" ]]
}

# is_ryoku_managed <path relative to ~/.config> <file with its content>: true
# for a file Ryoku owns.
is_ryoku_managed() {
    local rel="$1" file="$2" pattern
    for pattern in "${RYOKU_USER_OWNED[@]}"; do
        [[ "$rel" == $pattern ]] && return 1
    done
    for pattern in "${RYOKU_STATE[@]}"; do
        [[ "$rel" == $pattern ]] && return 0
    done
    if [[ -f "${RYOKU_SHIPPED}/${rel}" ]]; then
        if [[ -n "${RYOKU_OVERRIDE_FOR[$rel]:-}" ]] && ! cmp -s "${RYOKU_SHIPPED}/${rel}" "$file"; then
            RYOKU_WARNINGS+=("$rel")
        fi
        return 0
    fi
    head -n 3 "$file" 2>/dev/null | grep -qiE 'do not (hand-)?edit|generated by ryoku'
}
