/* Matugen OBS Studio Theme */
@qdata {
  bg: #1c1b19;
  fg: #f0e4c5;
  surface: #1c1b19;
  primary: #706e6b;
  accent: #a89984;
}

QWidget {
  background-color: #1c1b19;
  color: #f0e4c5;
}

QDockWidget {
  titlebar-close-icon: url(close.png);
  titlebar-normal-icon: url(undock.png);
  background-color: #1c1b19;
  color: #f0e4c5;
}

QPushButton {
  background-color: #3c3934;
  color: #706e6b;
  border: 1px solid #afa499;
  border-radius: 4px;
  padding: 4px 8px;
}

QPushButton:hover {
  background-color: #706e6b;
  color: #1c1b19;
}

QListWidget, QTreeWidget, QTextEdit {
  background-color: #2c2a27;
  color: #f0e4c5;
  border: 1px solid #666059;
}
