/* Matugen OBS Studio Theme */
@qdata {
  bg: #1E2326;
  fg: #D3C6AA;
  surface: #1E2326;
  primary: #A7C080;
  accent: #7FBBB3;
}

QWidget {
  background-color: #1E2326;
  color: #D3C6AA;
}

QDockWidget {
  titlebar-close-icon: url(close.png);
  titlebar-normal-icon: url(undock.png);
  background-color: #1E2326;
  color: #D3C6AA;
}

QPushButton {
  background-color: #2E383C;
  color: #A7C080;
  border: 1px solid #7A8478;
  border-radius: 4px;
  padding: 4px 8px;
}

QPushButton:hover {
  background-color: #A7C080;
  color: #1E2326;
}

QListWidget, QTreeWidget, QTextEdit {
  background-color: #262e31;
  color: #D3C6AA;
  border: 1px solid #4c544f;
}
